export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

export const FETCH_COMPLIANCE_TASK_START = "FETCH_COMPLIANCE_TASK_START";
export const FETCH_COMPLIANCE_TASK_SUCCESS = "FETCH_COMPLIANCE_TASK_SUCCESS";
