export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_COMPLIANCE_TASK_START = 'FETCH_COMPLIANCE_TASK_START';
export const FETCH_COMPLIANCE_TASK_SUCCESS = 'FETCH_COMPLIANCE_TASK_SUCCESS';

export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';

export const DELETE_COMPLIANCE_TASK = 'DELETE_COMPLIANCE_TASK';

export const UPDATE_COMPLIANCE_QUERY = 'UPDATE_COMPLIANCE_QUERY';
