from django.db import models
from django.contrib.auth.models import User


class Role(models.Model):
    Name = models.CharField(max_length=75)
    Permissions = models.CharField(max_length=1000)


class UserProject(models.Model):
    Name = models.CharField(max_length=75)
    Description = models.CharField(max_length=1000)
    ValidityDate = models.DateField()
    CompanyLogo = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100)


class UserData(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=75)
    Email = models.CharField(max_length=75)
    Organization = models.CharField(max_length=75, blank=True)
    Image = models.ImageField(upload_to=None, blank=True, height_field=None, width_field=None, max_length=100)
    JobDescription = models.CharField(max_length=300, blank=True)
    RoleValidity = models.DateField(blank=False, null=True)
    DATE_ENTERED = models.DateField(auto_now_add=True)
    RoleReference = models.ForeignKey(Role, on_delete=models.PROTECT, blank=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True)


class DefaultTemplate(models.Model):
    TableName = models.CharField(max_length=75)
    Items = models.CharField(max_length=1500)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True)


class SavedTemplate(models.Model):
    MappingName = models.CharField(max_length=75)
    MappedItems = models.CharField(max_length=1500)
    FileColumns = models.CharField(max_length=1500)
    DATE_ENTERED = models.DateField(auto_now_add=True)
    DataTableReference = models.ForeignKey(DefaultTemplate, on_delete=models.PROTECT, blank=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True)


class RuleEngine(models.Model):
    PRIORITY = models.CharField(max_length=75, blank=True)
    CATEGORY_LEVEL_ONE = models.CharField(max_length=75, blank=True)
    CATEGORY_LEVEL_TWO = models.CharField(max_length=75, blank=True)
    CATEGORY_LEVEL_THREE = models.CharField(max_length=75, blank=True)
    CATEGORY_LEVEL_FOUR = models.CharField(max_length=75, blank=True)
    CATEGORY_LEVEL_FIVE = models.CharField(max_length=75, blank=True)
    FIELD_1 = models.CharField(max_length=75, blank=True)
    OPERATOR_1 = models.CharField(max_length=75, blank=True)
    VALUE_1 = models.CharField(max_length=75, blank=True)
    FIELD_2 = models.CharField(max_length=75, blank=True)
    OPERATOR_2 = models.CharField(max_length=75, blank=True)
    VALUE_2 = models.CharField(max_length=75, blank=True)
    FIELD_3 = models.CharField(max_length=75, blank=True)
    OPERATOR_3 = models.CharField(max_length=75, blank=True)
    VALUE_3 = models.CharField(max_length=75, blank=True)
    STATUS = models.CharField(max_length=75, blank=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True)
    DATE_ENTERED = models.DateField(auto_now_add=True)


class RuleEngineHistory(models.Model):
    PRIORITY = models.CharField(max_length=75, blank=True, null=True)
    CATEGORIES_LEVELS = models.IntegerField(blank=True, null=True)
    ASSIGNED_CATEGORIES = models.CharField(max_length=400, blank=True, null=True)
    SEARCH_QUERY = models.CharField(max_length=500, blank=True, null=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True, null=True)
    RuleEngineReference = models.ForeignKey(RuleEngine, on_delete=models.PROTECT, blank=True, null=True)
    DATE_ENTERED = models.DateField(auto_now_add=True)


class InvoiceData(models.Model):
    INVOICE_ID = models.CharField(max_length=200, blank=False, null=True)
    GL_DATE = models.DateField(blank=True, null=True)
    INV_ORIGIN = models.CharField(max_length=200, blank=True, null=True)
    INV_DATE = models.DateField(blank=True, null=True)
    INV_SOURCE = models.CharField(max_length=200, blank=False, null=True)
    INV_NUMBER = models.CharField(max_length=200, blank=False, null=True)
    VENDOR_NUMBER = models.CharField(max_length=200, blank=False, null=True)
    VENDOR_NAME = models.CharField(max_length=200, blank=False, null=True)
    VENDOR_TYPE = models.CharField(max_length=200, blank=True, null=True)
    INV_TERMS = models.CharField(max_length=200, blank=True, null=True)
    LINE_NUMBER = models.CharField(max_length=200, blank=True, null=True)
    LINE_TYPE = models.CharField(max_length=200, blank=True, null=True)
    LINE_DESCRIPTION = models.CharField(max_length=1500, blank=False, null=True)
    LINE_QUANTITY = models.CharField(max_length=200, blank=False, null=True)
    LINE_UNIT_PRICE = models.FloatField(blank=True, null=True)
    LINE_UNIT_OF_MEASURE = models.CharField(max_length=200, blank=True, null=True)
    LINE_AMOUNT = models.FloatField(blank=False, null=True)
    GENERAL_LEDGER = models.CharField(max_length=200, blank=False, null=True)
    LOCATION = models.CharField(max_length=200, blank=True, null=True)
    DEPARTMENT = models.CharField(max_length=200, blank=True, null=True)
    ACCOUNT = models.CharField(max_length=200, blank=True, null=True)
    PO_NUMBER = models.CharField(max_length=200, blank=False, null=True)
    CREATION_DATE = models.DateField(blank=True, null=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True, null=True)
    RuleEngineReference = models.ForeignKey(RuleEngine, on_delete=models.PROTECT, blank=True, null=True)
    RULES_HISTORY = models.CharField(max_length=1200, blank=True, null=True)
    DATE_ENTERED = models.DateField(auto_now_add=True)


class TaxonomyData(models.Model):
    MAIN_CATEGORY = models.CharField(max_length=250)
    CATEGORY_LEVEL_ONE = models.CharField(max_length=75)
    CATEGORY_LEVEL_TWO = models.CharField(max_length=75)
    CATEGORY_LEVEL_THREE = models.CharField(max_length=75)
    CATEGORY_LEVEL_FOUR = models.CharField(max_length=75)
    CATEGORY_LEVEL_FIVE = models.CharField(max_length=75)
    CATEGORY_LEVELS = models.IntegerField()
    DATE_ENTERED = models.DateField(auto_now_add=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True, null=True)


class ContractData(models.Model):
    # FK="CONTRACT_NUMBER" with "VENDOUR_NUMBER" of invoice data
    # ---------------------DATES------------------------------
    CONTRACT_EXPIRY_DATE = models.DateField(blank=False, null=True)
    DATE_SIGNED = models.DateField(blank=False, null=True)
    COMMENCEMENT_DATE = models.DateField(blank=False, null=True)
    REVIEW_DATE = models.DateField(blank=True, null=True)
    PRICE_REVIEW_DATE = models.DateField(blank=True, null=True)
    CREATED_DATE = models.DateField(blank=False, null=True)
    MODIFIED_DATE = models.DateField(blank=False, null=True)
    CONTRACT_INC_EXPIRY_DATE = models.CharField(max_length=75, blank=True, null=True)
    # ------------------------STRINGS--------------------------
    SUPPLIER_NAME = models.CharField(max_length=75, blank=False, null=True)
    CONTRACT_NUMBER = models.CharField(max_length=75, blank=False, null=True)
    CONTRACT_TITLE = models.CharField(max_length=75, blank=True, null=True)
    SUPPLY_TYPE = models.CharField(max_length=75, blank=False, null=True)
    STATUS = models.CharField(max_length=75, blank=False, null=True)
    OWNER = models.CharField(max_length=75, blank=True, null=True)
    CONTRACT_ATTACHMENTS = models.CharField(max_length=75, blank=True, null=True)
    OTHER_ATTACHMENTS = models.CharField(max_length=75, blank=True, null=True)
    CONTRACT_INSURANCE_REQUIRED = models.CharField(max_length=75, blank=True, null=True)
    CONTRACT_RATES = models.CharField(max_length=75, blank=True, null=True)
    SUPPLIER_CONTRACT_NAME = models.CharField(max_length=75, blank=True, null=True)
    SUPPLIER_CONTRACT_PHONE = models.CharField(max_length=75, blank=True, null=True)
    SUPPLIER_CONTRACT_EMAIL = models.CharField(max_length=75, blank=True, null=True)
    SITE = models.CharField(max_length=75, blank=True, null=True)
    INITIAL_TERM = models.CharField(max_length=75, blank=True, null=True)
    ONGOING = models.CharField(max_length=75, blank=True, null=True)
    VALUE = models.CharField(max_length=75, blank=True, null=True)
    LOCATION_OF_HARD_COPY_CONTRACT_DOCUMENT = models.CharField(max_length=75, blank=True, null=True)
    NOTES = models.CharField(max_length=75, blank=True, null=True)
    CONTRACT_FORM = models.CharField(max_length=75, blank=True, null=True)
    IS_MANAGED_AS_PANEL_CONTRACTOR = models.CharField(max_length=75, blank=True, null=True)
    PANEL_RANKING = models.CharField(max_length=75, blank=True, null=True)
    CONTRACT_RISK = models.CharField(max_length=75, blank=True, null=True)
    CONTRACT_TYPES = models.CharField(max_length=75, blank=True, null=True)
    CONTRACT_STATUS = models.CharField(max_length=75, blank=False, null=True)
    CONTRACT_MANAGER = models.CharField(max_length=75, blank=False, null=True)
    CONTRACT_INITIATOR = models.CharField(max_length=75, blank=True, null=True)
    ADMINISTRATOR = models.CharField(max_length=75, blank=True, null=True)
    BUSINESS_REPRESENTATIVE = models.CharField(max_length=75, blank=True, null=True)
    PURCHASE_TYPE = models.CharField(max_length=75, blank=True, null=True)
    CONTRACT_ITEMS = models.CharField(max_length=75, blank=False, null=True)
    DIVISIONS = models.CharField(max_length=75, blank=True, null=True)
    REGIONS = models.CharField(max_length=75, blank=True, null=True)
    CREATED_BY = models.CharField(max_length=75, blank=True, null=True)
    MODIFIED_BY = models.CharField(max_length=75, blank=True, null=True)
    INSURANCE_TYPE = models.CharField(max_length=75, blank=True, null=True)
    DATE_ENTERED = models.DateField(auto_now_add=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True, null=True)


class GLOrgData(models.Model):
    # ----FK IS "LEDGER" WITH  "GENERAL_LEDGER" OF INVOICE TABLE-----
    LEDGER = models.CharField(max_length=100, blank=True, null=True)
    LEDGER_DESC = models.CharField(max_length=100, blank=True, null=True)
    STATE = models.CharField(max_length=100, blank=True, null=True)
    REGION = models.CharField(max_length=100, blank=True, null=True)
    DIVISION = models.CharField(max_length=100, blank=True, null=True)
    BUSINESS = models.CharField(max_length=100, blank=True, null=True)
    DATE_ENTERED = models.DateField(auto_now_add=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True, null=True)


class POData(models.Model):
    # ------------------FK = PO_NUMBER + PO_LINE_NUMBER----------
    # -------------------------DATES-----------------------------
    PO_CREATION_DATE = models.DateField(blank=False, null=True)

    REQ_APPROVED_DATE = models.DateField(blank=True, null=True)
    REQ_DATE = models.DateField(blank=True, null=True)
    PO_CLOSED_DATE = models.DateField(blank=True, null=True)
    PO_LAST_UPDATE_DATE = models.DateField(blank=True, null=True)
    PO_APPROVED_DATE = models.DateField(blank=True, null=True)
    PO_NEED_BY_DATE = models.DateField(blank=True, null=True)
    ORDER_LINE_CREATION_DATE = models.DateField(blank=True, null=True)
    FIRST_RECEIPT_DATE = models.DateField(blank=True, null=True)
    LAST_RECEIPT_DATE = models.DateField(blank=True, null=True)
    LAST_INV_DATE = models.DateField(blank=True, null=True)
    EARLIEST_INV_DATE = models.DateField(blank=True, null=True)
    LAST_CREATION_DATE = models.DateField(blank=True, null=True)
    EARLIEST_CREATION_DATE = models.DateField(blank=True, null=True)
    FIRST_APPROVED_DATE = models.DateField(blank=True, null=True)
    # ----------------------FLOATS--------------------------------
    HOLD_COUNT = models.FloatField(blank=True, null=True)
    DEL_LOCATION_ID = models.FloatField(blank=True, null=True)
    INVENTORY_ITEM_ID = models.FloatField(blank=True, null=True)
    # ----------------------NVARCHAR/Number-----------------------
    # ---Mandatory---
    PO_LINE_NUMBER = models.IntegerField(blank=False, null=True)
    QUANTITY_ORDERED = models.IntegerField(blank=False, null=True)
    QUANTITY_CANCELLED = models.IntegerField(blank=False, null=True)
    UNIT_PRICE = models.IntegerField(blank=False, null=True)
    AMOUNT_ORDERED = models.IntegerField(blank=False, null=True)
    QUANTITY_DELIVERED = models.IntegerField(blank=False, null=True)
    QUANTITY_DUE = models.IntegerField(blank=False, null=True)
    QUANTITY_BILLED = models.IntegerField(blank=False, null=True)
    AMOUNT_BILLED = models.IntegerField(blank=False, null=True)
    AMOUNT_RECEIPT = models.IntegerField(blank=False, null=True)
    AMOUNT_EXPECTED_RECEIPT = models.IntegerField(blank=False, null=True)
    AMOUNT_DUE = models.IntegerField(blank=False, null=True)
    UN_INVOICED_RECEIPT_AMOUNT = models.IntegerField(blank=False, null=True)

    #  ---Optional---
    BUYER_ID = models.IntegerField(blank=True, null=True)
    REQ_LINE_NUMBER = models.IntegerField(blank=True, null=True)
    ORDER_CYCLE_TIME_1 = models.IntegerField(blank=True, null=True)
    VENDOR_NUMBER = models.IntegerField(blank=True, null=True)
    DISTRIBUTION_NUM = models.IntegerField(blank=True, null=True)

    # ---------------------------CharField------------------------
    # ---Mandatory---
    PO_NUMBER = models.CharField(max_length=130, blank=False, null=True)
    PO_CLOSED_FLAG = models.CharField(max_length=130, blank=False, null=True)
    SUPPLIER_NAME = models.CharField(max_length=130, blank=False, null=True)
    HOLD_FLAG = models.CharField(max_length=130, blank=False, null=True)
    LEDGER_DESC = models.CharField(max_length=130, blank=False, null=True)
    LOCATION_DESC = models.CharField(max_length=130, blank=False, null=True)
    DEPARTMENT_DESC = models.CharField(max_length=130, blank=False, null=True)
    RECEIPT_STATUS = models.CharField(max_length=130, blank=False, null=True)

    # ---Optional---
    STATE = models.CharField(max_length=130, blank=True, null=True)
    BUSINESS = models.CharField(max_length=130, blank=True, null=True)
    HOLO_ENTITY_NAME = models.CharField(max_length=130, blank=True, null=True)
    BUYER = models.CharField(max_length=130, blank=True, null=True)
    REQUISITIONER = models.CharField(max_length=130, blank=True, null=True)
    REQUESTER = models.CharField(max_length=130, blank=True, null=True)
    PO_REQUESTER = models.CharField(max_length=130, blank=True, null=True)
    TRANSACTION_TYPE = models.CharField(max_length=130, blank=True, null=True)
    PURCHASING_STATUS = models.CharField(max_length=130, blank=True, null=True)
    PO_CONFIRMATION_FLAG = models.CharField(max_length=130, blank=True, null=True)
    REQ_NUMBER = models.CharField(max_length=130, blank=True, null=True)
    REQ_DESCRIPTION = models.CharField(max_length=130, blank=True, null=True)
    REQ_AUTHORISATION_STATUS = models.CharField(max_length=130, blank=True, null=True)
    PO_LAST_UPDATED_BY = models.CharField(max_length=130, blank=True, null=True)
    PO_LINE_CLOSED_FLAG = models.CharField(max_length=130, blank=True, null=True)
    PO_LINE_CLOSED_REASON = models.CharField(max_length=130, blank=True, null=True)
    PO_APPROVED_FLAG = models.CharField(max_length=130, blank=True, null=True)
    PO_APPROVED_PERIOD = models.CharField(max_length=130, blank=True, null=True)
    NINETY_DAYS_OLD = models.CharField(max_length=130, blank=True, null=True)
    VENDOR_ID = models.CharField(max_length=130, blank=True, null=True)
    SUPPLIER_SITE = models.CharField(max_length=130, blank=True, null=True)
    VENDOR_TYPE = models.CharField(max_length=130, blank=True, null=True)
    CONTRACTED_SUPPLIER = models.CharField(max_length=130, blank=True, null=True)
    CONTRACT_CATEGORY = models.CharField(max_length=130, blank=True, null=True)
    CONTRACT_END_DATE = models.CharField(max_length=130, blank=True, null=True)
    ON_HOLD = models.CharField(max_length=130, blank=True, null=True)
    LATEST_HOLD = models.CharField(max_length=130, blank=True, null=True)
    LATEST_HOLD_REASON = models.CharField(max_length=130, blank=True, null=True)
    LATEST_HOLD_DATE = models.CharField(max_length=130, blank=True, null=True)
    PURCHASING_CATEGORY1 = models.CharField(max_length=130, blank=True, null=True)
    PURCHASING_CATEGORY2 = models.CharField(max_length=130, blank=True, null=True)
    PO_ITEM_DESCRIPTION = models.CharField(max_length=130, blank=True, null=True)
    SUPPLIER_ITEM = models.CharField(max_length=130, blank=True, null=True)
    UOM = models.CharField(max_length=130, blank=True, null=True)
    CATALOG_TYPE = models.CharField(max_length=130, blank=True, null=True)
    CATALOG_SOURCE = models.CharField(max_length=130, blank=True, null=True)
    EXPENDITURE_TYPE = models.CharField(max_length=130, blank=True, null=True)
    ORGANISATION_CODE = models.CharField(max_length=130, blank=True, null=True)
    EAM_REF_NUMBER = models.CharField(max_length=130, blank=True, null=True)
    PO_EAM_REF_NUMBER = models.CharField(max_length=130, blank=True, null=True)
    PROJECT_NUMBER = models.CharField(max_length=130, blank=True, null=True)
    TASK_NUMBER = models.CharField(max_length=130, blank=True, null=True)
    LEDGER = models.CharField(max_length=130, blank=True, null=True)
    LOCATION = models.CharField(max_length=130, blank=True, null=True)
    DEPARTMENT = models.CharField(max_length=130, blank=True, null=True)
    ACCOUNT = models.CharField(max_length=130, blank=True, null=True)
    ACCOUNT_DESC = models.CharField(max_length=130, blank=True, null=True)
    PROCESS_STATUS = models.CharField(max_length=130, blank=True, null=True)
    LAST_RECEIPT_PERIOD = models.CharField(max_length=130, blank=True, null=True)
    LAST_INV_NO = models.CharField(max_length=130, blank=True, null=True)
    EARLIEST_INV_NO = models.CharField(max_length=130, blank=True, null=True)
    DEL_LOCATION_DESC = models.CharField(max_length=130, blank=True, null=True)
    NOTE_TO_VENDOR = models.CharField(max_length=130, blank=True, null=True)

    DATE_ENTERED = models.DateField(auto_now_add=True)
    UserProjectReference = models.ForeignKey(UserProject, on_delete=models.PROTECT, blank=True, null=True)
