# Generated by Django 3.1.4 on 2021-01-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedata',
            name='LINE_DESCRIPTION',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
