# Generated by Django 3.1.4 on 2021-01-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210102_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdata',
            name='DATE_ENTERED',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='glorgdata',
            name='DATE_ENTERED',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podata',
            name='DATE_ENTERED',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ruleengine',
            name='DATE_ENTERED',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ruleenginehistory',
            name='DATE_ENTERED',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savedtemplate',
            name='DATE_ENTERED',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxonomydata',
            name='DATE_ENTERED',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='DATE_ENTERED',
            field=models.DateField(auto_now_add=True),
        ),
    ]
