# Generated by Django 3.1.4 on 2021-01-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210102_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleengine',
            name='INVOICES_IMPACTED',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
