# Generated by Django 3.1.4 on 2021-01-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ruleengine_invoices_impacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleengine',
            name='INVOICES_IMPACTED',
        ),
    ]
