# Generated by Django 3.1.4 on 2021-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_ruleengine_invoices_impacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ProjectValidity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
