# Generated by Django 3.1.4 on 2021-01-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userdata_projectvalidity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='ProjectValidity',
            new_name='RoleValidity',
        ),
    ]
