# Generated by Django 3.1.4 on 2021-01-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210121_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='JobDescription',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Organization',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='RoleValidity',
            field=models.DateField(null=True),
        ),
    ]
