# Generated by Django 3.1.4 on 2021-01-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210121_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='ProjectReference',
            new_name='UserProjectReference',
        ),
    ]
