export const FETCH_PENDING_VEN_START = "FETCH_PENDING_VEN_START";
export const FETCH_PENDING_VEN_SUCCESS = "FETCH_PENDING_VEN_SUCCESS";

export const FETCH_APPROVED_VEN_START = "FETCH_APPROVED_VEN_START";
export const FETCH_APPROVED_VEN_SUCCESS = "FETCH_APPROVED_VEN_SUCCESS";

export const UPDATE_VENDOR_APPROVAL_STATUS = "UPDATE_VENDOR_APPROVAL_STATUS";

export const UPDATE_QUERY = "UPDATE_QUERY";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";

export const FETCH_CATEGORY_START = "FETCH_CATEGORY_START";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";

export const FETCH_TAGS_START = "FETCH_TAGS_START";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";

export const FETCH_TRADES_START = "FETCH_TRADES_START";
export const FETCH_TRADES_SUCCESS = "FETCH_TRADES_SUCCESS";

export const FETCH_DIVERSITY_START = "FETCH_DIVERSITY_START";
export const FETCH_DIVERSITY_SUCCESS = "FETCH_DIVERSITY_SUCCESS";

export const FETCH_PAYMENT_TERM_START = "FETCH_PAYMENT_TERM_START";
export const FETCH_PAYMENT_TERM_SUCCESS = "FETCH_PAYMENT_TERM_SUCCESS";

export const PARTIAL_UPDATE_VENDOR = "PARTIAL_UPDATE_VENDOR";
