export const FETCH_PENDING_VEN_START = "FETCH_PENDING_VEN_START";
export const FETCH_PENDING_VEN_SUCCESS = "FETCH_PENDING_VEN_SUCCESS";

export const UPDATE_VENDOR_APPROVAL_STATUS = "UPDATE_VENDOR_APPROVAL_STATUS";

export const UPDATE_QUERY = "UPDATE_QUERY";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
