# Generated by Django 3.1.7 on 2021-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_config', '0006_auto_20210504_0703'),
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbasicinfo',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='vendorbasic_cats_rev', to='vendor_management.Categories'),
        ),
        migrations.AlterField(
            model_name='vendorbasicinfo',
            name='diversity',
            field=models.ManyToManyField(blank=True, related_name='vendorbasic_diversity_rev', to='vendor_management.DiversityClassification'),
        ),
        migrations.AlterField(
            model_name='vendorbasicinfo',
            name='payment_term',
            field=models.ManyToManyField(blank=True, related_name='vendorbasic_payterm_rev', to='basic_config.PaymentTerm'),
        ),
        migrations.AlterField(
            model_name='vendorbasicinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='vendorbasic_tag_rev', to='vendor_management.VendorTags'),
        ),
        migrations.AlterField(
            model_name='vendorbasicinfo',
            name='trades',
            field=models.ManyToManyField(blank=True, related_name='vendorbasic_trade', to='vendor_management.Trades'),
        ),
    ]
