# Generated by Django 3.1.7 on 2021-04-28 18:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0003_auto_20210428_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vendorbasicinfo',
            managers=[
                ('ApprovedVendors', django.db.models.manager.Manager()),
            ],
        ),
    ]
