# Generated by Django 3.1.7 on 2021-04-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_config', '0004_delete_diversity'),
        ('vendor_management', '0004_auto_20210428_2338'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vendorbasicinfo',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='vendorbasicinfo',
            name='diversity',
        ),
        migrations.AddField(
            model_name='vendorbasicinfo',
            name='diversity',
            field=models.ManyToManyField(related_name='vendorbasic_diversity_rev', to='vendor_management.DiversityClassification'),
        ),
        migrations.RemoveField(
            model_name='vendorbasicinfo',
            name='payment_term',
        ),
        migrations.AddField(
            model_name='vendorbasicinfo',
            name='payment_term',
            field=models.ManyToManyField(related_name='vendorbasic_payterm_rev', to='basic_config.PaymentTerm'),
        ),
    ]
