# Generated by Django 3.1.7 on 2021-05-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0006_auto_20210504_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendortags',
            name='id',
        ),
        migrations.AlterField(
            model_name='vendortags',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
