# Generated by Django 3.1.7 on 2021-05-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0007_auto_20210504_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diversityclassification',
            name='name',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trades',
            name='name',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendortags',
            name='name',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
