export const FETCH_LIST_START = "FETCH_LIST_START";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";

export const ADD_TICKET = "ADD_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const EDIT_TICKET = "EDIT_TICKET";
export const UPLOAD_FILE = "UPLOAD_FILE";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const FETCH_FILE_UPLOADS_START = "FETCH_FILE_UPLOADS_START";
export const FETCH_FILE_UPLOADS_SUCCESS = "FETCH_FILE_UPLOADS_SUCCESS";

export const FETCH_CONTENT_HISTORY_START = "FETCH_CONTENT_HISTORY_START";
export const FETCH_CONTENT_HISTORY_SUCCESS = "FETCH_CONTENT_HISTORY_SUCCESS";
