export const FETCH_TICKETS_START = "FETCH_TICKETS_START";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";

export const ADD_TICKET = "ADD_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const EDIT_TICKET = "EDIT_TICKET";
export const UPLOAD_FILE = "UPLOAD_FILE";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const FETCH_FILE_UPLOADS_START = "FETCH_FILE_UPLOADS_START";
export const FETCH_FILE_UPLOADS_SUCCESS = "FETCH_FILE_UPLOADS_SUCCESS";

export const FETCH_CONTENT_HISTORY_START = "FETCH_CONTENT_HISTORY_START";
export const FETCH_CONTENT_HISTORY_SUCCESS = "FETCH_CONTENT_HISTORY_SUCCESS";

export const TICKET_ARCHIVE_TABLE_DATA = "TICKET_ARCHIVE_TABLE_DATA";
export const TICKET_ARCHIVE_PER_PAGE = "TICKET_ARCHIVE_PER_PAGE";
export const TICKET_ARCHIVE_CURRENT_PAGE = "TICKET_ARCHIVE_CURRENT_PAGE";
export const TICKET_ARCHIVE_TOTAL_ROWS = "TICKET_ARCHIVE_TOTAL_ROWS";

export const TICKET_ARCHIVE_FORM_QUERY = "TICKET_ARCHIVE_FORM_QUERY";
export const TICKET_ARCHIVE_RESET_STATES = "TICKET_ARCHIVE_RESET_STATES";

export const TICKET_ARCHIVE_TABLE_DATA_QUERY =
  "TICKET_ARCHIVE_TABLE_DATA_QUERY";

export const TICKET_ACTIVE_FORM_QUERY = "TICKET_ACTIVE_FORM_QUERY";
export const TICKET_ACTIVE_RESET_STATES = "TICKET_ACTIVE_RESET_STATES";

export const PARTIAL_UPDATE_TICKET = "PARTIAL_UPDATE_TICKET";
