# Generated by Django 3.1.1 on 2020-10-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDefaultTempletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templeteName', models.CharField(max_length=75)),
                ('templeteItems', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TaxomyDefaultTempletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxomyDefaulTempleteName', models.CharField(max_length=75)),
                ('taxomyDefaultTempleteItems', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TaxomySavedTempletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxomySavedTempleteName', models.CharField(max_length=75)),
                ('taxomySavedTempleteItems', models.CharField(max_length=1500)),
                ('taxomyDefaultTempleteReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.taxomydefaulttempletes')),
            ],
        ),
        migrations.CreateModel(
            name='TaxomyDataColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRIORITY', models.CharField(max_length=75)),
                ('MAIN_CATAGORY', models.CharField(max_length=250)),
                ('CATAGORY_LEVEL_ONE', models.CharField(max_length=75)),
                ('CATAGORY_LEVEL_TWO', models.CharField(max_length=75)),
                ('CATAGORY_LEVEL_THREE', models.CharField(max_length=75)),
                ('CATAGORY_LEVEL_FOUR', models.CharField(max_length=75)),
                ('CATAGORY_LEVEL_FIVE', models.CharField(max_length=75)),
                ('SCOPE', models.CharField(max_length=75)),
                ('TaxomyDefaultTempletesPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.taxomydefaulttempletes')),
                ('TaxomySavedTempletesPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.taxomysavedtempletes')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSavedTempletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SavedTempleteName', models.CharField(max_length=75)),
                ('SavedTempleteColumns', models.CharField(max_length=1500)),
                ('defaultTempleteReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.invoicedefaulttempletes')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDataColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVOICE_ID', models.CharField(max_length=75)),
                ('GL_DATE', models.DateField()),
                ('INV_ORGINE', models.CharField(blank=True, max_length=75)),
                ('INV_DATE', models.DateField()),
                ('INV_SOURCE', models.CharField(max_length=75)),
                ('INV_NUMBER', models.CharField(max_length=75)),
                ('VENDOR_NUMBER', models.CharField(max_length=75)),
                ('VENDOR_NAME', models.CharField(max_length=75)),
                ('VENDOR_TYPE', models.CharField(blank=True, max_length=75)),
                ('INV_TERMS', models.CharField(blank=True, max_length=75)),
                ('LINE_NUMBER', models.CharField(blank=True, max_length=75)),
                ('LINE_TYPE', models.CharField(blank=True, max_length=75)),
                ('LINE_DESCRIPTION', models.CharField(max_length=75)),
                ('LINE_QUANTITY', models.CharField(max_length=75)),
                ('LINE_UNIT_PRICE', models.FloatField(blank=True)),
                ('LINE_UNIT_OF_MEASURE', models.CharField(blank=True, max_length=75)),
                ('LINE_AMOUNT', models.FloatField()),
                ('GENERAL_LEDGER', models.CharField(max_length=75)),
                ('LOCATION', models.CharField(blank=True, max_length=75)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=75)),
                ('ACCOUNT', models.CharField(blank=True, max_length=75)),
                ('PO_NUMBER', models.CharField(max_length=75)),
                ('CREATION_DATE', models.DateField()),
                ('AllTempletesPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.invoicedefaulttempletes')),
                ('SavedTempletesPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.invoicesavedtempletes')),
            ],
        ),
    ]
