# Generated by Django 3.1.1 on 2020-09-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoiceColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVOICE_ID', models.CharField(max_length=75)),
                ('GL_DATE', models.DateField()),
                ('INV_ORGINE', models.CharField(blank=True, max_length=75)),
                ('INV_DATE', models.DateField()),
                ('INV_SOURCE', models.CharField(max_length=75)),
                ('INV_NUMBER', models.CharField(max_length=75)),
                ('VENDOR_NUMBER', models.CharField(max_length=75)),
                ('VENDOR_NAME', models.CharField(max_length=75)),
                ('VENDOR_TYPE', models.CharField(blank=True, max_length=75)),
                ('INV_TERMS', models.CharField(blank=True, max_length=75)),
                ('LINE_NUMBER', models.CharField(blank=True, max_length=75)),
                ('LINE_TYPE', models.CharField(blank=True, max_length=75)),
                ('LINE_DESCRIPTION', models.CharField(max_length=75)),
                ('LINE_QUANTITY', models.CharField(max_length=75)),
                ('LINE_UNIT_PRICE', models.FloatField(blank=True)),
                ('LINE_UNIT_OF_MEASURE', models.CharField(blank=True, max_length=75)),
                ('LINE_AMOUNT', models.FloatField()),
                ('GENERAL_LEDGER', models.CharField(max_length=75)),
                ('LOCATION', models.CharField(blank=True, max_length=75)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=75)),
                ('ACCOUNT', models.CharField(blank=True, max_length=75)),
                ('PO_NUMBER', models.CharField(max_length=75)),
                ('CREATION_DATE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedTempletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SavedTempleteName', models.CharField(max_length=75)),
                ('SavedTempleteColumns', models.CharField(max_length=75)),
            ],
        ),
    ]
