# Generated by Django 3.1.1 on 2020-09-23 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_invoicecolumns_savedtempletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecolumns',
            name='AllTempletesPK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapping.alltempletes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicecolumns',
            name='SavedTempletesPK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapping.savedtempletes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alltempletes',
            name='templeteItems',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedtempletes',
            name='SavedTempleteColumns',
            field=models.CharField(max_length=1000),
        ),
    ]
