# Generated by Django 3.1.1 on 2020-09-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_auto_20200923_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtempletes',
            name='defaultTempleteReference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapping.alltempletes'),
            preserve_default=False,
        ),
    ]
