export const FETCH_VENDORS_START = "FETCH_VENDORS_START";
export const FETCH_VENDORS_SUCCESS = "FETCH_VENDORS_SUCCESS";

export const UPDATE_QUERY = "UPDATE_QUERY";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";

export const UPDATE_PER_PAGE = "UPDATE_PER_PAGE";

export const FETCH_SINGLE_VENDOR_START = "FETCH_SINGLE_VENDOR_START";
export const FETCH_SINGLE_VENDOR_SUCCESS = "FETCH_SINGLE_VENDOR_SUCCESS";
