export const FETCH_VENDORS_START = "FETCH_VENDORS_START";
export const FETCH_VENDORS_SUCCESS = "FETCH_VENDORS_SUCCESS";

export const UPDATE_QUERY = "UPDATE_QUERY";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";

export const UPDATE_PER_PAGE = "UPDATE_PER_PAGE";

export const FETCH_SINGLE_VENDOR_START = "FETCH_SINGLE_VENDOR_START";
export const FETCH_SINGLE_VENDOR_SUCCESS = "FETCH_SINGLE_VENDOR_SUCCESS";

export const FETCH_INDIVIDUAL_VEN_ADDRESS_START =
  "FETCH_INDIVIDUAL_VEN_ADDRESS_START";
export const FETCH_INDIVIDUAL_VEN_ADDRESS_SUCCESS =
  "FETCH_INDIVIDUAL_VEN_ADDRESS_SUCCESS";

export const FETCH_FILE_UPLOAD_START = "FETCH_FILE_UPLOAD_START";
export const FETCH_FILE_UPLOAD_SUCCESS = "FETCH_FILE_UPLOAD_SUCCESS";

export const DELETE_VENDOR_UPLOAD = "DELETE_VENDOR_UPLOAD";

export const FETCH_NOTES_START = "FETCH_NOTES_START";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";

export const UPDATE_NOTE_QUERY = "UPDATE_NOTE_QUERY";

export const FETCH_REVIEW_LIST_START = "FETCH_REVIEW_LIST_START";
export const FETCH_REVIEW_LIST_SUCCESS = "FETCH_REVIEW_LIST_SUCCESS";

export const FETCH_VEN_REVIEW_LIST_START = "FETCH_VEN_REVIEW_LIST_START";
export const FETCH_VEN_REVIEW_LIST_SUCCESS = "FETCH_VEN_REVIEW_LIST_SUCCESS";

export const UPDATE_VEN_REVIEW_QUERY = "UPDATE_VEN_REVIEW_QUERY";

export const FETCH_VEN_COMPLIANCE_LIST_START =
  "FETCH_VEN_COMPLIANCE_LIST_START";
export const FETCH_VEN_COMPLIANCE_LIST_SUCCESS =
  "FETCH_VEN_COMPLIANCE_LIST_SUCCESS";

export const UPDATE_VEN_COMPLIANCE_QUERY = "UPDATE_VEN_COMPLIANCE_QUERY";
