# Generated by Django 3.1.7 on 2021-04-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessunit',
            old_name='bunit_name',
            new_name='buss_name',
        ),
    ]
