# Generated by Django 3.1.7 on 2021-04-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_config', '0003_auto_20210421_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diversity',
        ),
    ]
