# Generated by Django 3.1.7 on 2021-05-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_config', '0004_delete_diversity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentterm',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
