# Generated by Django 3.1.7 on 2021-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='archive',
            field=models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive')], default='Active', max_length=50),
        ),
    ]
