# Generated by Django 3.1.7 on 2021-04-03 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_auto_20210402_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_user_resperson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('resolved', 'resolved'), ('pending', 'pending'), ('in_progress', 'InProgress')], default='pending', max_length=20),
        ),
    ]
