# Generated by Django 3.1.7 on 2021-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20210403_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_color',
            field=models.CharField(max_length=100),
        ),
    ]
