# Generated by Django 3.1.7 on 2021-04-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20210407_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='lst_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='list',
            field=models.CharField(choices=[('Open_Tickets', 'Open Tickets'), ('In_Progress_Tickets', 'In Progress Tickets'), ('Resolved_Tickets', 'Resolved Tickets')], default='Open Tickets', max_length=50),
        ),
        migrations.DeleteModel(
            name='IndexHistory',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
