# Generated by Django 3.1.7 on 2021-04-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20210411_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='list',
            new_name='list_tickets',
        ),
    ]
