# Generated by Django 3.1.7 on 2021-04-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20210411_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_upload',
            name='ticket_file',
            field=models.FileField(upload_to=''),
        ),
    ]
