# Generated by Django 3.1.7 on 2021-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20210418_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_index',
            field=models.IntegerField(default=1),
        ),
    ]
