# Generated by Django 3.1.7 on 2021-04-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20210418_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_index',
        ),
    ]
