# Generated by Django 3.1.7 on 2021-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_remove_ticket_ticket_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='auto_inc_id',
            field=models.IntegerField(default=1),
        ),
    ]
