# Generated by Django 3.1.7 on 2021-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_auto_inc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='auto_inc_id',
            field=models.IntegerField(default=0),
        ),
    ]
