# Generated by Django 3.1.7 on 2021-04-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20210418_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='auto_inc_id',
            new_name='display_id',
        ),
    ]
